[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
portfolio_rebalancer = "9WXdcPPSeeCSBpTPjH4sAfHh5akRhnkQjhNusxymJa4H"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/simple-working-tests.ts"
